version: 0.1
phases:
  install:
    commands:
      - mkdir -p ~/.ssh
      - echo $KEY >> ~/.ssh/test_rsa
      - chmod 600 ~/.ssh/test_rsa
      - echo "StrictHostKeyChecking no" >> ~/.ssh/config
      - apt-get update
      - apt-get install -y openssh-client
      - eval "$(ssh-agent -s)" && ssh-add -k ~/.ssh/test_rsa
      - ssh -T git@github.com
  pre_build:
    commands:

  build:
    commands:
      - git submodule update --init --recursive

  post_build:
    commands:
